services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: coretech
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: coretech
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    image: node:latest
    ports:
      - "3030:3000"
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app
    command: "npm run dev"
    restart: always
